name: Build React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        node-version: [21.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy React to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: bitovi/github-actions-react-to-github-pages@4047c7f17e90e86c4daf2d49befd066f504df07c
        uses: bitovi/github-actions-react-to-github-pages@v1.2.1
        with:
          # Specifies if this action should checkout the code
          # checkout: # optional, default is true
          # Specifies the path of the static assets after building
          path: build
          # Specifies the command to run the installation.
          # install_command: # optional, default is npm ci
          # Specifies the command to run after the install command for the build
          # build_command: # optional, default is npm run build
